### ISSUE TITLE
the data sets

### ISSUE THREAD

**Issue by ZXXY09** [horvatovichlab/MSIWarp#13]
I want to know that how to download the four publicly available data sets

**Comment by horvatovichlab** [comment]
You need to go to ProteomeXchange and look for datasets PXD013860, PXD013069, PXD016146 (these IDs are unique you can also google them). At ProteoXchange on the dataset webpage there is an FTP link which can be used in FTP client like FileZilla. Good luck with the downloads.

**Comment by ZXXY09** [comment]
excuse me, how to get the orbitrap-desi data in the first example.
