### ISSUE TITLE
Interface to Cardinal or MALDIquant

### ISSUE THREAD

**Issue by jipeifeng** [horvatovichlab/MSIWarp#3]
Hi:
    Thank you for developing this software.
    Do you have designed interfaces to software, like Cardinal and MALDIquant. 
    By the way, an example is really appreciated.

Thank you!

Peifeng Ji

**Comment by j-o-eriksson** [comment]
Hi,

Thank you for your interest!

MSIWarp can be interfaced to Cardinal and MALDIQuant implicitly by loading and saving files in the .imzML format.

There is a complete example notebook of how to align a data set from MetaboLights in the example folder (warp_orbitrap_desi_imzml.ipynb).

The readme file also summarizes how to use MSIWarp together with pyimzML (although with the code to setup alignment parameters is omitted)

I hope those examples can help you!
Jonatan
