### ISSUE TITLE
MSIWarp on Maldi-TOF spectra

### ISSUE THREAD

**Issue by NoshineMo** [horvatovichlab/MSIWarp#8]
Hi !
Your package is great ! I would like to know if it works with MALDI-TOF spectra. I have tried on my spectra that I have to align but I do not know if my TypeError is because of my arguments or if the function is not adapted to MALDI-TOF spectra.
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-6f055a9baf6b> in <module>
      1 # find an m/z recalibration function for each spectrum
----> 2 recal_funcs = mx.find_optimal_warpings_uni(my_spectra,reference_spectrum,params, epsilon, n_cores)

TypeError: find_optimal_warpings_uni(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[List[msiwarp.msiwarp.peak]], arg1: List[msiwarp.msiwarp.peak], arg2: msiwarp.msiwarp.params_uniform, arg3: float, arg4: int) -> List[List[Tuple[float, float]]]

Invoked with: array([ 2001.16654336,  2001.58706881,  2001.99868969, ...,
       21022.27408836, 21023.63702209, 21025.        ]), array([ 1959.07152996,  1959.48760921,  1959.89487849, ...,
       20132.28967689, 20133.623449  , 20134.95726529]), parameters for node placement function, 1.5, 8`

Any idea ?

**Comment by j-o-eriksson** [comment]
Hi! 

It works on TOF data, provided that you can select a good reference spectrum.  So your error is likely related to how you setup your data. How do you initialize my_spectra, reference_spectrum, and params?

**Comment by NoshineMo** [comment]
Hey !
Thank you for your quick reply. You're right ! Actually the error may comes from how I initialized my_spectra and reference_spectrum that are both np.ndarrays of float (m/z values) and int (intensities). 
I just took a time to read warp.py code and I saw that I have to generate a list of MSIWarp spectra. 
Do you know how can I use to_mx_peaks() with list of m/z values that is np.ndarrays of float and intensities np.ndarrays of int ?
I get this when I use this function:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-c63824b42531> in <module>
      4 mz_begin = 1959
      5 mz_end = 20000
----> 6 my_spectra = [get_mx_spectrum(spectra['Masse m/z'].iloc[0], spectra['Intensite'].iloc[0], i, sigma_1, instrument_type) for i in range(len(spectra['Intensite'].iloc[0]))]

<ipython-input-20-c63824b42531> in <listcomp>(.0)
      4 mz_begin = 1959
      5 mz_end = 20000
----> 6 my_spectra = [get_mx_spectrum(spectra['Masse m/z'].iloc[0], spectra['Intensite'].iloc[0], i, sigma_1, instrument_type) for i in range(len(spectra['Intensite'].iloc[0]))]

~/.local/lib/python3.7/site-packages/msiwarp-0.1-py3.7-macosx-10.7-x86_64.egg/msiwarp/util/warp.py in get_mx_spectrum(file, meta, i, sigma_1, instrument_type)
     14     and instrument type.
     15     """
---> 16     s_i = read_spectrum_fs(file, meta[i])
     17     return to_mx_peaks(*s_i, sigma_1, id=i, instrument_type=instrument_type)
     18 

~/.local/lib/python3.7/site-packages/msiwarp-0.1-py3.7-macosx-10.7-x86_64.egg/msiwarp/util/read_sbd.py in read_spectrum_fs(filepath, meta_item)
     55     Tuple:tuple of mz and intensity vectors
     56     """
---> 57     with open(filepath, 'rb') as filestream:
     58         filestream.seek(meta_item[0])
     59         (mz, intensity) = read_spectrum(filestream, meta_item[1])

TypeError: expected str, bytes or os.PathLike object, not numpy.ndarray
`

About my params initialization: 
n_steps = 120
n_peaks = 80
max_n_nodes = 10
mz_begin = 1959
mz_end = 20000

n_cores = 4

sigma_1 = 1.5e-4
epsilon = 1.5
slack = 2.0 * epsilon * sigma_1
params = mx.params_uniform(mx.Instrument.TOF,
                           n_steps,
                           n_peaks,
                           max_n_nodes,
                           mz_begin,
                           mz_end,
                           slack)

**Comment by j-o-eriksson** [comment]
Provided that you have a an numpy array of m/z values and one of intensity values, you can use to_mx_peaks in the following manner:

`spectra = []`
`sigma_1 = <value>`

`for idx, mz, intensity in enumerate(zip(mz_array, intensity_array)):`
`   spectra.append(to_mx_peaks(mz, intensity,  sigma_1, id = idx, instrument_type = 'tof'))`

**Comment by NoshineMo** [comment]
Thanks for your answer !

**Comment by NoshineMo** [comment]
Hi !
Just reopening this issue about find_optimal_warpings_uni function. I want to find the optimal warping among 4 spectra for a first test.
The spectra size is 18000 each. Here are my parameters :
```
n_steps = 100
n_peaks = 80
max_n_nodes = 50
mz_begin = 1959
mz_end = 20000
n_cores = 80

sigma_1 = 1.5e-4
epsilon = 1.5
slack = 2.0 * epsilon * sigma_1
params = mx.params_uniform(mx.Instrument.TOF,
                           n_steps,
                           n_peaks,
                           max_n_nodes,
                           mz_begin,
                           mz_end,
                           slack)
reference_spectrum = spectra[2]
```
However this function ```recal_funcs = mx.find_optimal_warpings_uni(spectra,reference_spectrum,
                                           params, epsilon, n_cores)```is taking a too long time to run.(more than 30 min...) 
It not supposed to take so much time according to your paper and the examples on the notebooks. I have to stop the kernel every time I want to try it and so can't use this function. I thought I had to change the ```n_cores``` parameter (according warp_util.cpp code) to make it work but it don't.
Any idea what parameter I need to play with to make it work?

**Comment by NoshineMo** [comment]
problem solved.
